version: "3"
services:
  nginx:
    image: "tsungyu927/fib-nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"
  server:
    image: "tsungyu927/fib-server"
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_HOST=$POSTGRES_HOST
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_PORT=$POSTGRES_PORT
  client:
    image: "tsungyu927/fib-client"
    mem_limit: 128m
    hostname: client
  worker:
    image: "tsungyu927/fib-worker"
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
